### ISSUE TITLE
Suggestion: send com.android.camera.NEW_PICTURE after rename?

### ISSUE THREAD

**Issue by floe** [ciubex/dscautorename#2]
First of all, thanks for this very useful app!

I've had a persistent problem when the OwnCloud app is running in the background: when a new picture is taken, `com.android.camera.NEW_PICTURE` is detected both by OwnCloud and by DSC Autorename. However, the file is renamed faster than OwnCloud can upload it (and I would actually prefer the picture to be uploaded under its new name).

So my suggestion would be to also send `com.android.camera.NEW_PICTURE` by DSC Autorename after renaming has happened, just this time with the new name, so that other apps can then react to the _new_ file.

Opinions?

**Comment by floe** [comment]
For the record, this _should_ be possible with a single line of code: http://stackoverflow.com/a/3015574

In fact, OpenCamera does exactly the same: https://sourceforge.net/p/opencamera/code/ci/master/tree/src/net/sourceforge/opencamera/StorageUtils.java#l67

AFAICT, this shouldn't cause any issues - DSC AutoRename will ignore the second broadcast, as it doesn't match the usual pattern, and other apps will ignore the first broadcast, as the file is already gone. 

Perhaps I'll give it a try later today and submit a PR.

P.S. To round things off, it might also be an option to remove the old file from the MediaScanner database, see http://droidyue.com/blog/2014/01/19/scan-media-files-in-android/ and https://stackoverflow.com/questions/8379690/androids-media-scanner-how-do-i-remove-files

**Comment by ciubex** [comment]
Hi Florian,
Can you set the OwnCloud to upload files from a specific folder?If YES, you can set the DSC Autorename application to move the renamed file to another folder, if you open the pattern editor dialog, on the bottom is a check box which allow the user to specify if the renamed file should be moved or not. Also if you touch the path a dialog window should be open to select which folder should be used for moved files.
I'm using this to upload my own pictures automatically by the Photos Google app. The application detected new pictures folders and automatically take pictures from that folder.
It is that a solution?
Regards,Claudiu

```
  From: Florian Echtler <notifications@github.com>
```

 To: ciubex/dscautorename dscautorename@noreply.github.com 
 Sent: Monday, March 28, 2016 5:17 PM
 Subject: [dscautorename] Suggestion: send com.android.camera.NEW_PICTURE after rename? (#2)

First of all, thanks for this very useful app!I've had a persistent problem when the OwnCloud app is running in the background: when a new picture is taken, com.android.camera.NEW_PICTURE is detected both by OwnCloud and by DSC Autorename. However, the file is renamed faster than OwnCloud can upload it (and I would actually prefer the picture to be uploaded under its new name).So my suggestion would be to also send com.android.camera.NEW_PICTURE by DSC Autorename after renaming has happened, just this time with the new name, so that other apps can then react to the new file.Opinions?—

**Comment by floe** [comment]
> Can you set the OwnCloud to upload files from a specific folder?

Unfortunately, that's a feature that's not yet implemented...

I'll give my approach a try and see how this turns out.

**Comment by ciubex** [comment]
Hi Florian,
I do not use OwnCloud application, that's why I suggested to try to move files automatically to another folder and to check if the application OwnCloud is detecting that change (the path with the new renamed file).
I can add the broadcasting functionality into my app, but it's a workaround and not a real fix.Accordingly with Google Android API doc, the NEW_PICTURE message is send by camera applications only: linkThat's why I consider this solution as a workaround and not a real fix.
Normally the backup applications like OwnCloud should be able to allow the user to backup what they need and not to change other application to work with. Maybe this functionality is for payed versions, you should check with the developer of that application, too.
Are a lot of backup applications and is not not a good practice to modify an application based on needs of another one. The application should be adaptable to its own purposes.
Regards,Claudiu

**Comment by ciubex** [comment]
I implemented this request in the latest releases.

Thanks!

**Comment by floe** [comment]
Seems to work nicely, thanks!
